[package]
name = "bicat"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.4", features = ["json"] }
tokio = { version = "1.37.0", features = ["full"] }
serde = { version = "1.0.201", features = ["serde_derive"] }
serde_json = "1.0.117"
thiserror = "=1.0.60"